
footprint: [[0.33, 0.22], [0.33, -0.22], [-0.33, -0.22], [-0.33, 0.22]]

transform_tolerance: 0.2
map_type: costmap

#START VOXEL STUFF (copied from lattice planner)
# map_type: voxel
# origin_z: 0.0
# z_resolution: 0.2
# z_voxels: 10
# unknown_threshold: 9
# mark_threshold: 0
#END VOXEL STUFF

# params from lattice planner but not in tas file
# transform_tolerance: 0.3
# max_obstacle_height: 2.0
# footprint_padding: 0.01
# cost_scaling_factor: 10.0
# lethal_cost_threshold: 100


obstacle_layer:
 enabled: true
 raytrace_range: 3.5
 obstacle_range: 3.0
 inflation_radius: 0.2 #1.5
 track_unknown_space: false
 combination_method: 1
 
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_multi, marking: true, clearing: true}

inflation_layer:
 enabled: true
 cost_scaling_factor: 10.0
 inflation_radius: 0.5

static_layer:
 enabled: true
 map_topic: "/map"


