local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0 #50
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.05
  transform_tolerance: .2000


plugins: 
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

# params from lattice planner but not in tas file
# publish_voxel_map: true
# origin_x: 0.0
# origin_y: 0.0
